import * as React from "react"
// Imports the core function 'cva' and the type definition 'VariantProps' from the 
// 'class-variance-authority' library, which is used to build dynamic, variant-based Tailwind CSS classes.
import { cva, type VariantProps } from "class-variance-authority"

// Utility function (cn) for conditionally merging Tailwind CSS classes.
import { cn } from "@/lib/utils"

// -----------------------------------------------------------------------------
// 1. Alert Variants (Styling Definition using cva)
// -----------------------------------------------------------------------------

// Defines the base styles and available variants for the Alert component.
const alertVariants = cva(
  // Base classes applied to all alert components:
  // - relative: Sets position for absolute children (like the icon).
  // - w-full: Takes full width.
  // - rounded-lg, border, p-4: Standard styling for container box.
  // - [&>svg~*]:pl-7: Targets text/content that follows an SVG icon and adds left padding (for icon clearance).
  // - [&>svg+div]:translate-y-[-3px]: Fine-tunes the vertical alignment of content following the icon.
  // - [&>svg]:absolute [&>svg]:left-4 [&>svg]:top-4 [&>svg]:text-foreground: Positions and styles the optional SVG icon within the alert.
  "relative w-full rounded-lg border p-4 [&>svg~*]:pl-7 [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:left-4 [&>svg]:top-4 [&>svg]:text-foreground",
  {
    // Defines different visual styles based on the 'variant' prop.
    variants: {
      variant: {
        // Default style (light background, standard text color).
        default: "bg-background text-foreground",
        // Destructive style (red-focused border and text), commonly used for errors or warnings.
        destructive:
          "border-destructive/50 text-destructive dark:border-destructive [&>svg]:text-destructive",
      },
    },
    // Sets the default variant to be used if the 'variant' prop is not specified.
    defaultVariants: {
      variant: "default",
    },
  }
)

// -----------------------------------------------------------------------------
// 2. Alert Component (Root Container)
// -----------------------------------------------------------------------------

// The main Alert component, which renders the container with the generated styling.
const Alert = React.forwardRef<
  HTMLDivElement,
  // Merges standard HTML div attributes with the types generated by cva for the 'variant' prop.
  React.HTMLAttributes<HTMLDivElement> & VariantProps<typeof alertVariants>
>(({ className, variant, ...props }, ref) => (
  <div
    ref={ref}
    // Ensures accessibility by semantically identifying this element as an alert.
    role="alert"
    // cn merges the base alert styles (generated by alertVariants based on the 'variant' prop)
    // with any custom className provided by the user.
    className={cn(alertVariants({ variant }), className)}
    {...props}
  />
))
Alert.displayName = "Alert"

// -----------------------------------------------------------------------------
// 3. Alert Title Component
// -----------------------------------------------------------------------------

// Component for the main heading/title within the alert.
const AlertTitle = React.forwardRef<
  HTMLParagraphElement, // Note: This ref type is often used for h-tags for semantic consistency in libraries.
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h5
    ref={ref}
    // Styling for a small, medium-weight heading with slight margin/spacing adjustments.
    className={cn("mb-1 font-medium leading-none tracking-tight", className)}
    {...props}
  />
))
AlertTitle.displayName = "AlertTitle"

// -----------------------------------------------------------------------------
// 4. Alert Description Component
// -----------------------------------------------------------------------------

// Component for the body text/description content within the alert.
const AlertDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    // Styling ensures small text size and sets relaxed line height for inner <p> tags.
    className={cn("text-sm [&_p]:leading-relaxed", className)}
    {...props}
  />
))
AlertDescription.displayName = "AlertDescription"

// -----------------------------------------------------------------------------
// 5. Exports
// -----------------------------------------------------------------------------

export { Alert, AlertTitle, AlertDescription }
